use_default_settings:
  engines:
    keep_only:
      - google
      - bing
      - duckduckgo
      - wikipedia

search:
  formats:
    - html
    - json
  safe_search: 0
  autocomplete: ""

server:
  secret_key: "CHANGE-ME-TO-A-RANDOM-SECRET"
  limiter: true
  image_proxy: true
  method: "GET"

valkey:
  url: redis://firecrawl-redis:6379/1

ui:
  static_use_hash: true

doi_resolvers:
  oadoi.org: "https://oadoi.org/"
  doi.org: "https://doi.org/"

default_doi_resolver: "oadoi.org"
